### PR TITLE
CS-229 - need this in source control :)

### PR DESCRIPTION
**Pull request by JimTomlinson-UW**
Ack, I thought you'd checked this in; my bad.

### CODE REVIEW

**Review by goulter — CHANGES_REQUESTED** [review]
The change I had was to .`claro .dijitContentPane`, but if this change also makes the scroll bar work, then great.

**Comment by JimTomlinson-UW** [comment]
I don't grok css, nor dojo, nor the toolchain, but the only .dijitContentPane I see in the source is where I mod'd.tundra .dijitContentPane {
    padding: 2px;
    overflow: auto;
}
Maybe that’s the source that gets transmogrified to what we saw in the browser?

**Comment by goulter** [comment]
> I really don't grok css, nor dojo, but the only .dijitContentPane I see in the source is where I mod'd src/main/webapp/css/iam-dojo-2.css
> `.tundra .dijitContentPane { `
> Is there an aliasing I'm missing?

Hmmm, let's do a quick screen share when you have time today and we'll double check.

**Comment by JimTomlinson-UW** [comment]
Okay, should be good to merge now

**Review by goulter — APPROVED** [review]

**Pull request merged**
