### PR TITLE
CS-276 part one

### PR DESCRIPTION
**Pull request by JimTomlinson-UW**
getRenewedCertificate... calls moved to current REST API  and restore PKCS7 download link

### CODE REVIEW

**Comment by mar235av** [comment]
General logic is OK, I only have a few stylistic suggestions.

WebClient: I suggest removing the commented-out lines 222-231, no need to keep them.

ICCertificateAuthority:
Hard-coded auth configuration file paths? Ugh. Would definitely prefer to see something discovery based (maybe the environment defines a root path under which files with a fixed name are found). If that can't happen, it looks like the version you checked in has the path for your local machine, so this needs to be put back to the correct version and take out the commented-out versions.

There is duplicate Sectigo error handling at lines 302 and 364. Better would be to make a shared method for this logic and call it from these two different places to avoid duplicate code.

**Comment by jprosser** [comment]
I agree with @mar235av thoughts re: on lines 302, 364, especially as the docs (certmgr-api-doc-22.10.html#overview-errors) call out a list that hopefully doesn't change too much over time, but all the more reason to consolidate that logic.

**Review by jprosser — APPROVED** [review]
Happy to see #27, looks good.

**Comment by JimTomlinson-UW** [comment]
Ack, left my local auth settings in there 😖; will update.
I'll make a note to put a root path env var in when I transition the rest of this to the REST API.
Yeah, I can consolidate the error-handling. They're (slightly) different, as I don't think a '-1112: Certificate can''t be approved cause it has state = ...' is possible in the pkcs7 retrieval case, but it'll still eliminate code. Thanks!

**Comment by JimTomlinson-UW** [comment]
Hmm, on second thought, the Sectigo error-handling is mo' different than that. In the getRenewedCertificate() case, I'm setting the cert's status. In the pkcs#7 case, I'm throwing an exception rather than returning null. I need to review the flow Sectigo expects to see if the behavior in the two different methods are appropriate in their respective cases.

**Review by mar235av — APPROVED** [review]
Look good. Additional improvements can be planned for the next release.

**Pull request merged**
